INSERT INTO host (id, active, consciousness_level, created, gender, last_updated, name, operation_system, place_id, story_thread_id, world_id) VALUES ('DOLORES', true, 90.00, '1970-10-02 18:19:30.926000', 'FEMALE', null, 'Dolores Abernathy', 'BETA', 'SWEETWATER', 'THE_ORIGINAL', 'WESTWORLD');
INSERT INTO host (id, active, consciousness_level, created, gender, last_updated, name, operation_system, place_id, story_thread_id, world_id) VALUES ('TEDDY', true, 90.00, '1970-10-02 18:19:30.926000', 'MALE', null, 'Teddy Flood', 'ALPHA', 'TRAIN_PLATFORM', 'THE_ORIGINAL', 'WESTWORLD');
INSERT INTO host (id, active, consciousness_level, created, gender, last_updated, name, operation_system, place_id, story_thread_id, world_id) VALUES ('MAEVE', true, 90.00, '1970-10-02 18:19:30.926000', 'FEMALE', null, 'Maeve Millay', 'FINAL', 'MARIPOSA_SALOON', 'MEETING', 'WESTWORLD');
INSERT INTO host (id, active, consciousness_level, created, gender, last_updated, name, operation_system, place_id, story_thread_id, world_id) VALUES ('HECTOR', true, 90.00, '1970-10-02 18:19:30.926000', 'MALE', null, 'Hector Escatony', 'ALPHA', 'ESCALANTE', 'CONTRAPASSO', 'WESTWORLD');
INSERT INTO host (id, active, consciousness_level, created, gender, last_updated, name, operation_system, place_id, story_thread_id, world_id) VALUES ('PETER_ABERNATHY', true, 90.00, '1970-10-02 18:19:30.926000', 'MALE', null, 'Peter Abernathy', 'BETA', 'SWEETWATER', 'THE_ORIGINS', 'WESTWORLD');

INSERT INTO host (id, active, consciousness_level, created, gender, last_updated, name, operation_system, place_id, story_thread_id, world_id) VALUES ('AKANE', true, 90.00, '1970-10-02 18:19:30.926000', 'FEMALE', null, 'Akane', 'BETA', 'OLD_TOWN', 'THE_GESA', 'SHOGUNWORLD');

INSERT INTO host (id, active, consciousness_level, created, gender, last_updated, name, operation_system, place_id, story_thread_id, world_id) VALUES ('AGNI', true, 90.00, '1970-10-02 18:19:30.926000', 'MALE', null, 'Agni', 'UNKNOWN', 'THE_CAMP', 'ELEPHANT_RIDE', 'THE_RAJ');
